coordinator=false

http-server.http.port=8080
discovery.uri=http://trino:8080
internal-communication.https.required=true
http-server.https.enabled=true
http-server.https.port=8443

# Shared Secret
internal-communication.shared-secret=${ENV:COM_KEY}
