connector.name=delta_lake
hive.metastore.uri=thrift://metastore:9083
fs.native-azure.enabled=true

azure.auth-type=OAuth
azure.oauth.tenant-id=${ENV:AZURE_TENANT_ID}
azure.oauth.endpoint=https://login.microsoftonline.com/${ENV:AZURE_TENANT_ID}/oauth2/v2.0/token
azure.oauth.client-id=${ENV:AZURE_CLIENT_ID}
azure.oauth.secret=${ENV:AZURE_CLIENT_SECRET}

delta.register-table-procedure.enabled=true
